name: Github Actions 실행시켜보기

# Event : 실행되는 시점 설정
# main 브랜치에 push 될 때 Workflow 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow 는 하나 이상의 Job 으로 구성
# 여러 Job 은 기본적으로 병렬 수행.
jobs:
  # Job 식별을 위한 id
  My-Deploy-Job:
    # ubuntu 환경 / 가장 최신 버전 선택
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job 은 여러 Step 들로 구성
    steps:
      - name: Hello World 찍기
        run : echo "Hello World"

      - name: 여러 명령어 문장 작성
        run: |
          echo "Good"
          echo "Morning"